---
title: "GDP Growth"
author: "Frida Gomam"
date: '2020-12-01T21:13:14-05:00'
categories: R
tags:
- R Markdown
- plot
- regression
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

# GDP Growth

```{r gdp_2015}

library(dplyr)
library(ggplot2)
library(viridis)
#library(hrbrthemes)
#library(tree)
#library(treemapify)


gdp_2015 <- 
  read.csv("data/gdp_production_2015.csv") %>% 
  select(Sector, CODE1, PERIOD, DTVAL_CO) %>%
  arrange(desc(PERIOD, CODE1)) %>% 
  mutate(DTVAL_CO_LAG = lead(DTVAL_CO, 44)) %>%
  mutate(QoQ = round((DTVAL_CO/DTVAL_CO_LAG-1)*100,1)) %>% 
  filter(PERIOD>="2016-03-31", CODE1!=1) %>%
  group_by(PERIOD) %>%
  mutate(share = DTVAL_CO_LAG/sum(DTVAL_CO_LAG)) %>%
  mutate(share_qoq = round(QoQ*share,1)) %>%
  mutate(growth = ifelse(share_qoq<0, "negative", "positive"))

gdp_plot <- 
  ggplot(
    data = gdp_2015,
    aes(
      x = PERIOD,
      y = share_qoq,
      fill = Sector
      )
  ) + 
  geom_bar(
    stat = "identity",
    position = "stack", 
  ) +
  labs(title = "GROSS DOMESTIC GROWTH",
       subtitle = "Quarterly YoY Growth (%)",
       x="", y="", 
       caption = "@sansar_b, Data Source: National Statistic Office Of Mongolia") +
  theme_classic() + 
  theme(
    #plot.title = element_text(size = 12, face = "bold"),
    legend.title = element_text(size = 9),
    legend.text = element_text(size = 8)
    )

gdp_plot


```

